git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  allBranchesLogCmds:
    - git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium --oneline
  log:
    showGraph: always
    showWholeGraph: true
gui:
  expandFocusedSidePanel: true
os:
  edit: "nvim"
customCommands:
  - key: "C"
    command: '~/.claude/local/single-commit'
    context: "files"
    description: "AI-generated commit with Claude Code"
  - key: "B"
    command: '~/.claude/local/batch-commit'
    context: "files"
    description: "Batch unstaged changes into logical commits"
